import fs from 'node:fs';
import {marked} from '/home/virant/dev/rakuensoftware-web/node_modules/marked/lib/marked.esm.js';
import {chromium} from '/tmp/transport-final-review/node_modules/playwright-core/index.mjs';
const article = '/home/virant/dev/rakuen-blog-private/articles/everything-crosses-one-transport/article/everything-crosses-one-transport.md';
const raw = fs.readFileSync(article, 'utf8');
const body = raw.replace(/^---\n[\s\S]*?\n---\n/, '');
const css = fs.readFileSync('/home/virant/dev/rakuensoftware-web/node_modules/@rakuensoftware/smoothgui/dist/smoothgui.css','utf8') + fs.readFileSync('/home/virant/dev/rakuensoftware-web/src/site.css','utf8');
const html = `<!doctype html><html lang="en" data-theme="light"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Everything Crosses One Transport — local editorial preview</title><style>${css}body{margin:0;padding:24px;background:var(--sg-bg);color:var(--sg-text)}main{max-width:760px;margin:auto}h1{font-size:38px}</style><main><h1>Everything Crosses One Transport</h1><div class="sg-prose">${marked.parse(body)}</div></main></html>`;
fs.writeFileSync('/tmp/transport-final-review-final/preview.html',html);
const browser = await chromium.launch({executablePath:'/home/virant/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox'],env:{...process.env,LD_LIBRARY_PATH:'/tmp/wol-blender-deps/root/usr/lib/x86_64-linux-gnu:/tmp/aimee-providers-browser/libs/usr/lib/x86_64-linux-gnu'}});
const page = await browser.newPage({viewport:{width:1000,height:1000}});
await page.setContent(html);
const checks = {browser:await browser.version(),figures:await page.locator('figure').count(),svg:await page.locator('svg').count(), desktop: await page.evaluate(()=>({viewport:innerWidth,bodyWidth:document.body.scrollWidth}))};
checks.labelsOutsideSVG = await page.evaluate(()=>Array.from(document.querySelectorAll('svg text')).filter(t=>{const b=t.getBBox(),v=t.ownerSVGElement.viewBox.baseVal;return b.x<0 || b.y<0 || b.x+b.width>v.width || b.y+b.height>v.height}).map(t=>t.textContent));
for (let i=0;i<4;i++) await page.locator('figure').nth(i).screenshot({path:`/tmp/transport-final-review-final/figure-${i+1}.png`});
await page.setViewportSize({width:390,height:844});
checks.mobile = await page.evaluate(()=>({viewport:innerWidth,bodyWidth:document.body.scrollWidth,scrollRegions:Array.from(document.querySelectorAll('figure [role=region]')).map(x=>({client:x.clientWidth,scroll:x.scrollWidth,tabindex:x.tabIndex}))}));
await page.locator('figure').first().screenshot({path:'/tmp/transport-final-review-final/mobile.png'});
await page.evaluate(()=>document.documentElement.setAttribute('data-theme','dark'));
await page.setViewportSize({width:1000,height:1000});
await page.locator('figure').nth(2).screenshot({path:'/tmp/transport-final-review-final/dark.png'});
fs.writeFileSync('/tmp/transport-final-review-final/checks.json',JSON.stringify(checks,null,2)+'\n');
console.log(JSON.stringify(checks,null,2));
await browser.close();
